name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of web-ifc are you running?
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: files
    attributes:
      label: Anything else?
      description: |
        Model? Links? Screenshots? Anything that will give us more context about the issue you are encountering!
        It is very useful to understand how the model should look - so screenshots of this are very helpful.
        Please attach the model if you can. If you want to exchange it privately please contact us on discord.
        Tip: You can attach files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false