name: Feature
description: New feature ideas & enhancements
title: "[Feat]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to improve web-ifc!
  - type: textarea
    id: feature
    attributes:
      label: What is your idea?
      description: Tell us about the new feature!
    validations:
      required: true