name: C++ Build and Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    
    runs-on: ${{matrix.os-type}}
    
    strategy:
      matrix:
        os-type: [ubuntu-24.04]
        configuration: [Release]    
    
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        sudo apt update
        sudo apt install gcc-13 g++-13
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 --slave /usr/bin/g++ g++ /usr/bin/g++-13 --slave /usr/bin/gcov gcov /usr/bin/gcov-13
        sudo update-alternatives --set gcc /usr/bin/gcc-13
    - name: Configure
      working-directory: ${{github.workspace}}/src/cpp
      run: cmake -B ${{github.workspace}}/src/cpp/Build -DCMAKE_BUILD_TYPE=${{matrix.configuration}}
    - name: Build
      working-directory: ${{github.workspace}}/src/cpp
      run: cmake --build ${{github.workspace}}/src/cpp/Build --config ${{matrix.configuration}}
    - name: Test
      working-directory: ${{github.workspace}}/src/cpp/Build
      run: ctest -VV -C ${{matrix.configuration}} -L web-ifc
